backend:
  name: github
  repo: ElijahBitkov/zohan_site
  branch: netify
  
media_folder: /src/markdown-pages/
public_folder: markdown-pages
  
collections:
  - name: blog
    label: Blog
    folder: "src/markdown-pages/"
    media_folder: "image"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}/index"
    create: true
    fields:
      - { name: path, label: Path }
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: image, widget: image, label: Image }
      - { name: body, label: Body, widget: markdown }
      - { name: featuredImage, widget: hidden, default: ./banner.jpg }
      
