backend:
  name: github
  repo: ElijahBitkov/zohan_site
  branch: netify
  
media_folder: /src/markdown-pages/
public_folder: markdown-pages
publish_mode: editorial_workflow
  
collections:
  - name: blog
    label: Blog
    folder: "src/markdown-pages/"
    media_folder: "."
    slug: "{{year}}-{{month}}-{{day}}-{{hour}}-{{minute}}-{{second}}-{{slug}}/index"
    create: true
    fields:
      - { name: path, label: Path }
      - { name: slug, label: Slug }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: image, widget: image, label: Image, default: ./default.jpg}
      - { name: body, label: Body, widget: markdown }
      - { name: featuredImage, default: ../default.jpg }
      
